---
version: '3.0'
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.2.2
    ports:
      - 9100:9100
    command:
      --path.rootfs=/host
    volumes:
      - "/:/host:ro,rslave"
    pid: host
